AdvanceWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('AdvanceWebPortal.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdvanceWebPortal/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "AdvanceWebPortal"
urlpatterns = [
    url(r'^$', views.get_index_page, name='get_index_page'),
    # auth urls
    url(r'^login/$', views.hotel_login, name='hotel_login'),
    url(r'^register/$', views.hotel_register, name='hotel_register'),
    url(r'^logout/$', views.logout, name='logout'),
    # room urls
    url(r'^rooms/$', views.get_rooms, name='get_rooms'),
    url(r'^add/room/$', views.get_add_room_form, name='get_add_room_form'),
    url(r'^create/room/$', views.create_room, name='create_room'),
    url(r'^room/details/(?P<room_id>[0-9]+)/$', views.get_room_details, name='get_room_details'),
    url(r'^room/update/(?P<room_id>[0-9]+)/$', views.get_update_room_details_form, name='get_update_room_details_form'),
    url(r'^update/room/(?P<room_id>[0-9]+)/$', views.update_room_details, name='update_room_details'),
    url(r'^delete/room/(?P<room_id>[0-9]+)/$', views.delete_room, name='delete_room'),
    # hotel urls
    url(r'^hotel/details/$', views.get_hotel_details, name='get_hotel_details'),
    url(r'^hotel/update/$', views.get_update_hotel_details_form, name='get_update_hotel_details_form'),
    url(r'^update/hotel/$', views.update_hotel_details, name='update_hotel_details'),

    #RESTAPI URLs
    url(r'^fbAuthRegister/', views.FacebookAuthRegister.as_view()),
    url(r'^fbAuthLogin/', views.FacebookAuthLogin.as_view()),
    url(r'^search/', views.SearchForRooms.as_view()),
    url(r'^rooms/(?P<room_id>[0-9]+)/', views.Rooms.as_view()),
    url(r'^bids/', views.Bids.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

AdvanceWebPortal/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _

# Create your models here.
# AdvanceWebPortal models

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        # This is a private function
        # It is going to be a reusable function used to create both admin users and normal users using email for auth

        if not email:
            raise ValueError("The email provided must not be empty!")
        
        # checks email is valid
        email = self.normalize_email(email)
        user = self.model(
            email = email,
            is_active = True,
            is_staff = is_staff,
            is_superuser = is_superuser,
            last_login = timezone.now(),
            date_joined = timezone.now(),
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)

class Hotel(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=254, blank=True)
    address_line_1 = models.CharField(max_length=1024, blank=True, null=True)
    address_line_2 = models.CharField(max_length=1024, blank=True, null=True)
    town_city = models.CharField(max_length=1024)
    county = models.CharField(max_length=1024, blank=True, null=True)
    postcode = models.CharField(max_length=20)
    country = models.CharField(max_length=1024)
    telephone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    # setting that email is to be used as the unique identifier for a user
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name',]

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('hotel')
        verbose_name_plural = _('hotels')


    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

def image_location(room, file):
    return '{0}/Room_{1}/{2}'.format('Room_Images', room.id, file)

def upload_image(instance, file):
    return '{0}/Room_{1}/{2}'.format('Room_Images', instance.room.id, file)

class Room(models.Model):
    room_number = models.IntegerField()
    room_name = models.CharField(max_length=1024)
    room_size = models.CharField(max_length=100)
    room_description = models.TextField()
    valid_for_bid_from = models.DateField(auto_now=False, auto_now_add=False)
    valid_for_bid_until = models.DateField(auto_now=False, auto_now_add=False)
    currency = models.CharField(max_length=100)
    starting_bid_price = models.DecimalField(max_digits=10, decimal_places=2)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    leading_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    main_room_image = models.FileField(upload_to=image_location, null=True, blank=True)
    booked = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    @property
    def get_images(self):
        return Image.objects.get(room=self)

    def __str__(self):
        return "{} - {}".format(str(self.room_number), self.room_name)

class Image(models.Model):
    name = models.CharField(max_length=1024)
    ext = models.CharField(max_length=100, null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    room_image = models.FileField(upload_to=upload_image, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}{}".format(self.name, self.ext)

class AppUser(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    account_type = models.CharField(max_length=30)
    device_id = models.CharField(max_length=254, unique=True)
    gcm_registration_id = models.CharField(max_length=254, unique=True)

    def __str__(self):
        return "{} - {}".format(self.name, self.email)

class Bid(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} bid for {} - {}".format(self.app_user.name, self.room.room_name, str(self.room.room_number))

class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    check_in_date = models.DateField(auto_now=False, auto_now_add=False)
    check_out_date = models.DateField(auto_now=False, auto_now_add=False)
    valid_for_bid_again = models.BooleanField(default=False)
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return "{} booked by {} for {}-{}".format(self.room, self.app_user, self.room.currency, self.amount)

AdvanceWebPortal/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import *
from .serializers import *
from django.contrib import auth
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth import login
from django.utils import timezone
from decimal import Decimal
from django.conf import settings
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from Equitum.Crypto.my_hasher import *
from Equitum.PaymentsAPI.braintree_api import BraintreeAPI
from Equitum.Tempus.datetime import *
from Equitum.FCM.FCM import FCM

import os
import shutil

# Create your views here.
# AdvanceWebPortal views

def get_index_page(request):
    return render(request, 'index.html')

def hotel_register(request):
    hotel_name = request.POST['hotel_name']
    town_city = request.POST['town_city']
    postcode = request.POST['postcode']
    country = request.POST['country']
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']

    if not hotel_name or not town_city or not postcode or not country or not email or not password or not confirm_password:
        data = {'hotel_name':hotel_name, 'town_city':town_city, 'postcode':postcode, 'country':country, 'email':email, 'password':password, 'confirm_password':confirm_password}
        messages.info(request, 'All Form Fields Are Required!')
        return render(request, 'index.html', data)
    
    try:
        if Hotel.objects.get(email=email):
            data = {'hotel_name':hotel_name, 'town_city':town_city, 'postcode':postcode, 'country':country, 'email':email, 'password':password, 'confirm_password':confirm_password}
            messages.info(request, 'Email Address Already Exists! \n Please Login')
            return render(request, 'index.html', data)
    except Hotel.DoesNotExist:
        pass

    if password == confirm_password:
        extra_fields = {}
        extra_fields["name"] = hotel_name
        extra_fields["town_city"] = town_city
        extra_fields["postcode"] = postcode
        extra_fields["country"] = country

        hotel = Hotel.objects.create_user(email, password, **extra_fields)
        return render(request, 'rooms.html', RequestContext(request, {'hotel' : hotel}))

    data = {'hotel_name':hotel_name, 'town_city':town_city, 'postcode':postcode, 'country':country, 'email':email, 'password':password, 'confirm_password':confirm_password}
    messages.info(request, 'Passwords Do Not Match!')
    return render(request, 'index.html', data)

def hotel_login(request):
    email = request.POST['email']
    password = request.POST['password']

    if not email or not password:
        messages.info(request, 'All Form Fields Are Required!')
        return render(request, 'index.html', {'email':email, 'password':password})

    hotel = auth.authenticate(username=email, password=password)

    if hotel is not None:
        auth.login(request, hotel)
        return HttpResponseRedirect('/rooms')

    messages.info(request, 'Invalid Login Details!')
    return render(request, 'index.html', {'email':email, 'password':password})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

def get_add_room_form(request):
    if request.user.is_authenticated():
        return render(request, 'add_room.html', {'hotel' : request.user})
    return HttpResponseRedirect('/')

def create_room(request):
    if request.user.is_authenticated():
        hotel = Hotel.objects.get(email=request.user)
        list_of_images = request.FILES.getlist('room_images')
        main_room_image = list_of_images[0]

        new_room = Room.objects.create(
            room_number = request.POST.get('room_number', ''),
            room_name = request.POST.get('room_name', ''),
            room_size = request.POST.get('room_size', ''),
            room_description = request.POST.get('room_description', ''),
            valid_for_bid_from = request.POST.get('valid_for_bid_from', timezone.now),
            valid_for_bid_until = request.POST.get('valid_for_bid_until', timezone.now),
            currency = request.POST.get('currency', ''),
            starting_bid_price = Decimal(request.POST.get('starting_price', 0.00)),
            hotel = hotel
        )

        room = Room.objects.get(pk=new_room.id)
        image_location(room, main_room_image)
        room.main_room_image = main_room_image
        room.save()

        for room_image in list_of_images:
            if room_image == main_room_image:
                continue

            image_name, image_ext = os.path.splitext(room_image.name)

            new_image = Image.objects.create(
                name = image_name,
                ext = image_ext,
                room = room
            )

            image = Image.objects.get(pk=new_image.id)
            upload_image(image, room_image)
            image.room_image = room_image
            image.save()

        return HttpResponseRedirect('/rooms')
    return HttpResponseRedirect('/')

def get_rooms(request):
    if request.user.is_authenticated():
        rooms = Room.objects.filter(hotel=request.user)
        return render(request, 'rooms.html', {'hotel': request.user, 'rooms': rooms})
    return HttpResponseRedirect('/')
    

def get_room_details(request, room_id):
    if request.user.is_authenticated():
        room = get_object_or_404(Room, pk=room_id)
        images = get_list_or_404(Image, room=room)
        return render(request, 'room_details.html', {'hotel': request.user, 'room': room, 'images': images})
    return HttpResponseRedirect('/')

def get_update_room_details_form(request, room_id):
    if request.user.is_authenticated():
        room = get_object_or_404(Room, pk=room_id)        
        return render(request, 'update_room_details.html', {'hotel': request.user, 'room': room})
    return HttpResponseRedirect('/')

def update_room_details(request, room_id):
    if request.user.is_authenticated():
        hotel = Hotel.objects.get(email=request.user)
        room = get_object_or_404(Room, pk=room_id)

        room.room_number = request.POST.get('room_number', '')
        room.room_name = request.POST.get('room_name', '')
        room.room_size = request.POST.get('room_size', '')
        room.room_description = request.POST.get('room_description', '')
        room.valid_for_bid_from = request.POST.get('valid_for_bid_from', timezone.now)
        room.valid_for_bid_until = request.POST.get('valid_for_bid_until', timezone.now)
        room.currency = request.POST.get('currency', '')
        room.starting_bid_price = request.POST.get('starting_bid_price', 0.00)
        room.save()

        return HttpResponseRedirect('/rooms')
    return HttpResponseRedirect('/')

def delete_room(request, room_id):
    if request.user.is_authenticated():
        room = get_object_or_404(Room, pk=room_id)
        shutil.rmtree(os.path.join(settings.MEDIA_ROOT, 'Room_Images', 'Room_'+str(room.id)))
        room.delete()

        return HttpResponseRedirect('/rooms')
    return HttpResponseRedirect('/')

def get_hotel_details(request):
    if request.user.is_authenticated():
        return render(request, 'hotel_details.html', {'hotel': request.user})
    return HttpResponseRedirect('/')

def get_update_hotel_details_form(request):
    if request.user.is_authenticated():
        return render(request, 'update_hotel_details.html', {'hotel': request.user})
    return HttpResponseRedirect('/')

def update_hotel_details(request):
    if request.user.is_authenticated():
        hotel = Hotel.objects.get(email=request.user)

        hotel.address_line_1 = request.POST.get('address_line_1', '')
        hotel.address_line_2 = request.POST.get('address_line_2', '')
        hotel.town_city = request.POST.get('town_city', '')
        hotel.county = request.POST.get('county', '')
        hotel.postcode = request.POST.get('postcode', '')
        hotel.telephone_number = request.POST.get('telephone_number', '')
        hotel.save()

        return HttpResponseRedirect('/hotel/details')
    return HttpResponseRedirect('/')

# RESTAPI Views
# url - fbAuthRegister/
class FacebookAuthRegister(APIView):
    def post(self, request):
        app_user = AppUser.objects.create(
            name=request.data["name"],
            email=request.data["email"],
            account_type=request.data["account_type"],
            device_id = hash_device_key(),
            gcm_registration_id=request.data["gcm_registration_id"]
        )

        return Response({'Message': 'Login Successful!', 'UserDetails': AppUserSerializer(app_user).data})

# url - fbAuthLogin/
class FacebookAuthLogin(APIView):
    def post(self, request):
        try:
            app_user = AppUser.objects.get(email=request.data["email"])

            if app_user.gcm_registration_id == request.data["gcm_registration_id"]:
                return Response({'Message': 'Login Successful!', 'UserDetails': AppUserSerializer(app_user).data})
            
            app_user.gcm_registration_id = request.data["gcm_registration_id"]
            app_user.save()
            return Response({'Message': 'Login Successful!', 'UserDetails': AppUserSerializer(app_user).data})
        except AppUser.DoesNotExist:
            return Response({'Message': 'Unauthorized User!'})

# url - search/
class SearchForRooms(APIView):
    def post(self, request):
        try:
            app_user = AppUser.objects.get(device_id=request.META.get('HTTP_AUTHORIZATION'))
            rooms = []
            images = []
            bids = []

            # get hotels in the searched city
            hotels = Hotel.objects.filter(town_city=request.data["town_city"])

            for hotel in hotels:
                # get rooms offered for bid by hotels

AdvanceWebPortal/templates/add_room.html
{% extends 'base.html' %}
{% block title %}Add Room{% endblock %}
{% block content %}    
    <div class="span6">
        <div class="col-xs-2"></div>
    </div>

    <div class="span6">
        <div class="col-xs-5">
            <form action="/create/room/" method="POST" enctype="multipart/form-data">
                {% csrf_token %}	
                <label for="room_number">Room Number</label><br/>
                <input type="text" class="form-control" name="room_number" id="room_number" placeholder="Room Number" />
                <br/>
                <label for="room_name">Room Name (Optional)</label><br/>
                <input type="text" class="form-control" name="room_name" id="room_name" placeholder="Room Name" />
                <br/>
                <label for="room_size">Room Size</label><br/>
                <select class="form-control" name="room_size" id="room_size">
                    <option value="Select">Select</option>
                    <option value="Single Room">Single Room</option>
                    <option value="Double Room">Double Room</option>
                    <option value="Family Room">Family Room</option>
                </select>
                <br/>
                <label for="room_description">Room Description</label><br/>
                <textarea class="form-control" rows="10" cols="50" name="room_description" id="room_description"></textarea>
                <br/>
                <label for="currency">Currency</label><br/>
                <select class="form-control" name="currency" id="currency">
                    <option value="Select">Select</option>
                    <option value="British Pound">British Pound</option>
                    <option value="US Dollar">US Dollar</option>
                    <option value="Euro">Euro</option>
                </select>
                <br/>
                <label for="starting_price">Starting Price</label><br/>
                <input type="text" class="form-control" name="starting_price" placeholder="Starting Price" />
                <br/>
                <label for="valid_for_bid_from">Valid For Bid From</label><br/>
                <input type="date" class="form-control" name="valid_for_bid_from" />
                <br/>
                <label for="valid_for_bid_until">Valid For Bid Until</label><br/>
                <input type="date" class="form-control" name="valid_for_bid_until" />
                <br/>
                <label for="room_images">Upload Room Images</label><br/>
                <input type="file" name="room_images" multiple/>
                <br/>
                <strong><input type="submit" class="form-control" value="Add Room" /></strong>
	        </form>
        </div>
    </div>
{% endblock %}

AdvanceWebPortal/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                {% if hotel.is_authenticated %}
                    <!-- Logo -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/rooms/">ADVANCE WEB PORTAL</a>
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Nav Bar Links -->
                    <div id="navbar-main" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="/rooms/">Rooms</a></li>
                            <li><a href="/add/room/">Add Room</a></li>
                        </ul>

                        <div class="row">
                            <div class="col-xs-7">
                                <p class="navbar-text navbar-right"><a href="/hotel/details/">{{ hotel.name }}</a></p>
                            </div>

                            <div class="col-xs-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li><a href="/logout/">LogOut</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <!-- Logo -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">ADVANCE WEB PORTAL</a>
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                {% endif %}
            </div>
        </nav>
        <div class="container-fluid">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

AdvanceWebPortal/templates/hotel_details.html
{% extends 'base.html' %}
{% block title %}Hotel{% endblock %}
{% block content %}
    <div class="span6">
        <div class="col-xs-1"></div>
    </div>

    <div class="span6">
        <div class="row">
            <div class="col-xs-3">
                <h3><strong>Name:</strong></h3>
                <h3><strong>Address Line 1:</strong></h3>
                <h3><strong>Address Line 2:</strong></h3>
                <h3><strong>Town/City:</strong></h3>
                <h3><strong>County:</strong></h3>
                <h3><strong>Postcode:</strong></h3>
                <h3><strong>Country:</strong></h3>
                <h3><strong>Telephone Number:</strong></h3>
            </div>
            <div class="col-xs-3">
                <h3>{{ hotel.name }}</h3>

                {% if not hotel.address_line_1 %}
                    <h3>Not set</h3>
                {% else %}
                    <h3>{{ hotel.address_line_1}}</h3>
                {% endif %}

                {% if not hotel.address_line_2 %}
                    <h3>Not set</h3>
                {% else %}
                    <h3>{{ hotel.address_line_2}}</h3>
                {% endif %}

                <h3>{{ hotel.town_city }}</h3>

                {% if not hotel.county %}
                    <h3>Not set</h3>
                {% else %}
                    <h3>{{ hotel.county }}</h3>
                {% endif %}

                <h3>{{ hotel.postcode }}</h3>
                <h3>{{ hotel.country }}</h3>

                {% if not hotel.telephone_number %}
                    <h3>Not set</h3>
                {% else %}
                    <h3>{{ hotel.telephone_number }}</h3>
                {% endif %}
            </div>
        </div>
    </div>
    
    <br/><br/>
    <div class="span6">
        <div class="col-xs-1"></div>
    </div>

    <div class="col-xs-3">
        <a href="{% url 'AdvanceWebPortal:get_update_hotel_details_form' %}"><button type="button" class="form-control"><strong>Update Hotel Details</strong></button></a>
    </div>
{% endblock %}

AdvanceWebPortal/templates/room_details.html
{% extends 'base.html' %}
{% block title %}Room Details{% endblock %}
{% block content %}
    <div class="span6">
        <div class="col-xs-1"></div>
    </div>

    <div class="span6">
        <div class="row">
            <div class="col-xs-3">
                <h3><strong>Room Number:</strong></h3>
                <h3><strong>Room Name:</strong></h3>
                <h3><strong>Room Size:</strong></h3>
                <h3><strong>Room Description:</strong></h3>
                <h3><strong>Valid For Bid From:</strong></h3>
                <h3><strong>Valid For Bid Until:</strong></h3>
                <h3><strong>Currency:</strong></h3>
                <h3><strong>Starting Bid Price:</strong></h3>
            </div>
            <div class="col-xs-3">
                <h3>{{ room.room_number }}</h3>
                <h3>{{ room.room_name }}</h3>
                <h3>{{ room.room_size }}</h3>
                <h3>{{ room.room_description }}</h3>
                <h3>{{ room.valid_for_bid_from }}</h3>
                <h3>{{ room.valid_for_bid_until }}</h3>
                <h3>{{ room.currency }}</h3>
                <h3>{{ room.starting_bid_price }}</h3>
            </div>

            <div class="col-xs-4">
                <img src="{{ room.main_room_image.url }}" class="img-responsive" id="image_size">

                {% if images %}
                    {% for image in images %}
                        <img src="{{ image.room_image.url }}" class="img-responsive" id="image_size">
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="col-xs-1"></div>
    </div>
    
    <div class="span6">
        <div class="row">
            <div class="col-xs-3">
                <a href="{% url 'AdvanceWebPortal:get_update_room_details_form' room.id %}"><button type="button" class="form-control"><strong>Update Room Details</strong></button></a>
            </div>
            <div class="col-xs-3">
                <a href="{% url 'AdvanceWebPortal:delete_room' room.id %}"><button type="button" class="form-control" style="background-color:red;color:white"><strong>Delete Room</strong></button></a>
            </div>
        </div>
    </div>
{% endblock %}

AdvanceWebPortal/templates/rooms.html
{% extends 'base.html' %}
{% block title %}Rooms{% endblock %}
{% block content %}
    <div class="span6">
        <div class="col-xs-1"></div>
    </div>

    <div class="span6">
        <div class="col-xs-7">
            {% if rooms %}
                <table class="table">
                    <thead>
                        <tr>
                            <!--<th>Room Image</th>
                            <th>Room</th>
                            <th>Option</th>-->
                        </tr>
                    </thead>
                    <tbody>
                        {% for room in rooms %}
                            <tr>
                                <td><img src="{{ room.main_room_image.url }}" class="img-responsive" id="thumbnail_size"></td>
                                <td><h3><a href="{% url 'AdvanceWebPortal:get_room_details' room.id %}">{{ room.id }} - {{ room.room_number }} - {{ room.room_name }}</a></h3></td>
                                <td><br/><a href="{% url 'AdvanceWebPortal:delete_room' room.id %}"><button type="button" class="form-control" style="background-color:red;color:white"><strong>Delete Room</strong></button></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h2>No rooms have been uploaded!</h2>
            {% endif %}
        </div>
    </div>
{% endblock %}